---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Apt for Repo addition
  package:
    name: ["python-apt"]
    state: latest

- name: Install traceroute
  apt:
    name: traceroute
    update_cache: yes
    state: latest

- name: Install ssmping
  apt:
    name: ssmping
    state: latest

- name: Flush Handlers, best practice
  meta: flush_handlers
