---

- name: Install traceroute
  apt:
    name: traceroute
    update_cache: yes
    state: latest

- name: Install ssmping
  apt:
    name: ssmping
    state: latest

- name: Flush Handlers, best practice
  meta: flush_handlers
