---

- name: Install traceroute
  apt:
    name: traceroute
    update_cache: yes
    state: latest

- name: Install iperf2
  apt:
    name: iperf
    state: latest

- name: Flush Handlers, best practice
  meta: flush_handlers
