---
- name: Copy server01 interfaces configuration
  template:
    src: interfaces-server01.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking
  when: inventory_hostname == "server01"

- name: Copy server05 interfaces configuration
  template:
    src: interfaces-server05.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking
  when: inventory_hostname == "server05"

- name: Sleep for server to disconnect
  pause:
    seconds: 5

- name: Flush Handlers, best practice
  meta: flush_handlers
